// <auto-generated />
namespace UniplanProject_G03.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RefactorModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefactorModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202011131145099_RefactorModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
