//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniplanProject_G03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public System.DateTime Curdate { get; set; }
        public string Writer { get; set; }
        public int Countread { get; set; }
        public string Topic { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string UserName { get; set; }
        public string Urlimg { get; set; }
    }
}
